[manifest]
version = "0.0.~1"
dump_lua = true
priority = 0

# Replace draw hand

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''
self:emplace(card, nil, stay_flipped)
'''
position = 'before'
match_indent = true
payload = '''
if BerryLegendaries and area == G.deck and self == G.hand and card and G.jokers and G.jokers.cards then
	for _,v in ipairs(G.jokers.cards) do
		-- Bread card check
		if v.ability.name == 'j_blurb_bread' and (pseudorandom(pseudoseed('bread')) < (G.GAME.probabilities.normal / v.ability.extra.odds)) then
			-- Bread's oubler
			card.ability.perma_bonus = card.ability.perma_bonus + card:get_chip_bonus()
			v.ability.extra.has_doubled = true
		end
		
		-- Qui card check
		if v.ability.name == 'j_blurb_qui' and card.base.suit == 'Diamonds' and not card.debuff then
			v.ability.extra.diamond_count = v.ability.extra.diamond_count or 0
			v.ability.extra.diamond_count = v.ability.extra.diamond_count + 1
		end
	end
end
'''

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
if G.load_shop_jokers then 
'''
position = 'after'
match_indent = true
payload = '''
if BerryLegendaries then sendDebugMessage(tprint(G.load_shop_jokers), 'BerryLogger') end
'''