[manifest]
version = "0.0.~1"
dump_lua = true
priority = 0

# Replace draw hand

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''
self:emplace(card, nil, stay_flipped)
'''
position = 'before'
match_indent = true
payload = '''
if BerryLegendaries and area == G.deck and self == G.hand and card then
	SMODS.calculate_context({berry_card_drawn = true, other_card = card})
end
'''

# Zohnathan load jokers to shop?

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
if G.load_shop_jokers then 
'''
position = 'before'
match_indent = true
payload = '''
if BerryLegendaries then sendDebugMessage(tprint(G.load_shop_jokers), 'BerryLogger') end
'''

# Patch Cryptid ascended check for Nyala

[[patches]]
[patches.pattern]
target = '=[SMODS Cryptid "lib/ascended.lua"]'
pattern = '''
if G.GAME.cry_exploit_override then
	G.GAME.current_round.current_hand.cry_asc_num = G.GAME.current_round.current_hand.cry_asc_num + 1
end
'''
position = 'after'
match_indent = true
payload = '''
if BerryLegendaries and G.GAME.current_round.current_hand.cry_asc_num > 0 then SMODS.calculate_context({berry_is_ascended = true}) end
'''